import "./globals.css";

export const metadata = {
  title: "Sucoding",
  description: "Generated by Me" 
}

export default async function RootLayout ({children} : {children: React.ReactNode}) {
  return(
    <html lang="en">
      <body>
        <header>Root Header</header>
        {children}
        <footer>Root Footer</footer>
      </body>
    </html>
  )
}