import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <Link href={"/"}>Home</Link>
            <Link href={"/products"}>Products</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
 