import Navbar from "@/components/common/Navbar";
import "../css/globals.css";
import Footer from "@/components/common/Footer";
import { createClient } from "@/lib/supabase/server";
import AuthProvider from "@/context/AuthProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body>
        <AuthProvider user={user}>
          <div className="flex flex-col min-h-screen bg-[#0D1117] text-[#c9d1d9]">
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
